"""Backoffice batch 1 — i18n keys for the 4 features in 5 locales.
Idempotent merger: existing keys are kept, only gaps are filled.
"""
import json
from pathlib import Path

MSG_DIR = Path(__file__).resolve().parent / "apps" / "backoffice" / "messages"

TRANSLATIONS = {
    "tr": {
        "cmdk": {"placeholder":"Sayfa, ürün, kullanıcı, kategori ara…","noResults":"Sonuç bulunamadı","groupQuickActions":"Hızlı eylemler","groupPages":"Sayfalara git","groupProducts":"Ürünler","groupCategories":"Kategoriler","groupUsers":"Kullanıcılar","groupSwitchTenant":"Restoran değiştir","actionNewOrder":"Yeni Sipariş","actionPublishMenu":"Menü Yayınla","actionMwstReport":"Vergi Raporu Çıkar (MWST)"},
        "setupProgress": {"pill":"Kurulum %{percent}","title":"Kurulum İlerlemesi","subtitle":"{done}/{total} adım tamamlandı","complete":"Kurulum tamam","dismiss":"Gizle","optional":"opsiyonel","steps":{"tenant_created":"Restoran oluşturuldu","admin_user":"İlk yönetici hesabı yaratıldı","tenant_info":"Restoran bilgileri eklendi (adres / telefon)","opening_hours":"Açılış saatleri ayarlandı","first_category":"İlk kategori eklendi","first_product":"İlk ürün eklendi","tax_profile":"Vergi profili ayarlandı","receipt_template":"Fiş şablonu seçildi","payment_method":"Ödeme yöntemi yapılandırıldı","pos_device":"POS cihazı bağlandı","first_staff":"İlk personel eklendi"}},
        "reasonCodes": {"title":"Sebep Kodları","subtitle":"POS'ta sipariş iptali (void) ve indirim uygulamasında sunulan sebep listeleri.","tabVoid":"İptal sebepleri","tabDiscount":"İndirim sebepleri","addReason":"Yeni sebep","editReason":"Sebebi düzenle","formHint":"Code benzersiz olmalı (örn. WRONG_ORDER). Her dilde label girilebilir.","labelsLabel":"Diller","labelPlaceholder":"{locale} etiket","colCode":"Kod","colLabelTr":"TR etiket","colOrder":"Sıra","colApproval":"Onay gerekli?","colMaxPercent":"Max %","colStatus":"Durum","colActions":"İşlemler","yesApproval":"Evet","noApproval":"Hayır","statusActive":"Aktif","statusInactive":"Pasif","requiresApprovalLabel":"Müdür onayı gerekli","maxPercentLabel":"Maksimum indirim oranı (%)","maxPercentHint":"Bu sebepte uygulanabilecek en yüksek indirim. Boş = sınırsız.","emptyState":"Henüz sebep tanımlı değil. Yeni sebep ekleyin.","createSuccess":"Sebep oluşturuldu","updateSuccess":"Sebep güncellendi","deleteSuccess":"Sebep silindi","deleteError":"Silinemedi","saveError":"Kaydedilemedi","deleteConfirmBody":"{code} kodlu sebep silinecek. Devam edilsin mi?"},
        "menu": {"snoozeColumn":"Stok Durumu","statusAvailable":"Mevcut","statusSnoozed":"Tükendi","snoozedUntil":"Bitiş:","snoozeBulk":"{count} ürün için durum","snoozeFor":"Süre seç","snooze1h":"1 saat tükendi","snooze2h":"2 saat tükendi","snoozeEod":"Gün sonuna kadar tükendi","snoozeManual":"Manuel iptal edene kadar tükendi","snoozeClear":"Mevcut yap (tüm seçilenler)"},
        "nav": {"rmReasonCodes":"Sebep Kodları"},
    },
    "en": {
        "cmdk": {"placeholder":"Search pages, products, users, categories…","noResults":"No results","groupQuickActions":"Quick actions","groupPages":"Go to page","groupProducts":"Products","groupCategories":"Categories","groupUsers":"Users","groupSwitchTenant":"Switch restaurant","actionNewOrder":"New Order","actionPublishMenu":"Publish Menu","actionMwstReport":"Export Tax Report (MWST)"},
        "setupProgress": {"pill":"Setup {percent}%","title":"Setup Progress","subtitle":"{done}/{total} steps complete","complete":"Setup complete","dismiss":"Dismiss","optional":"optional","steps":{"tenant_created":"Restaurant created","admin_user":"First admin account created","tenant_info":"Restaurant info filled in (address / phone)","opening_hours":"Opening hours configured","first_category":"First category added","first_product":"First product added","tax_profile":"Tax profile configured","receipt_template":"Receipt template selected","payment_method":"Payment method configured","pos_device":"POS device paired","first_staff":"First staff member added"}},
        "reasonCodes": {"title":"Reason Codes","subtitle":"Pickers shown in the POS when voiding an order or applying a manual discount.","tabVoid":"Void reasons","tabDiscount":"Discount reasons","addReason":"New reason","editReason":"Edit reason","formHint":"Code must be unique (e.g. WRONG_ORDER). Per-locale labels are optional.","labelsLabel":"Languages","labelPlaceholder":"{locale} label","colCode":"Code","colLabelTr":"TR label","colOrder":"Order","colApproval":"Approval?","colMaxPercent":"Max %","colStatus":"Status","colActions":"Actions","yesApproval":"Yes","noApproval":"No","statusActive":"Active","statusInactive":"Inactive","requiresApprovalLabel":"Requires manager approval","maxPercentLabel":"Max discount percent (%)","maxPercentHint":"Maximum discount permitted with this reason. Blank = unlimited.","emptyState":"No reasons defined yet. Add a new one.","createSuccess":"Reason created","updateSuccess":"Reason updated","deleteSuccess":"Reason deleted","deleteError":"Delete failed","saveError":"Save failed","deleteConfirmBody":"Reason {code} will be deleted. Continue?"},
        "menu": {"snoozeColumn":"Availability","statusAvailable":"Available","statusSnoozed":"Sold out","snoozedUntil":"Until:","snoozeBulk":"Status for {count} items","snoozeFor":"Duration","snooze1h":"Sold out 1 hour","snooze2h":"Sold out 2 hours","snoozeEod":"Sold out until end of day","snoozeManual":"Sold out until manual reset","snoozeClear":"Make available (all selected)"},
        "nav": {"rmReasonCodes":"Reason Codes"},
    },
    "de": {
        "cmdk": {"placeholder":"Seiten, Produkte, Benutzer, Kategorien suchen…","noResults":"Keine Ergebnisse","groupQuickActions":"Schnellaktionen","groupPages":"Seite öffnen","groupProducts":"Produkte","groupCategories":"Kategorien","groupUsers":"Benutzer","groupSwitchTenant":"Restaurant wechseln","actionNewOrder":"Neue Bestellung","actionPublishMenu":"Menü veröffentlichen","actionMwstReport":"Steuerbericht exportieren (MWST)"},
        "setupProgress": {"pill":"Setup {percent}%","title":"Setup-Fortschritt","subtitle":"{done}/{total} Schritte erledigt","complete":"Setup abgeschlossen","dismiss":"Ausblenden","optional":"optional","steps":{"tenant_created":"Restaurant erstellt","admin_user":"Erstes Admin-Konto erstellt","tenant_info":"Restaurant-Daten erfasst (Adresse / Telefon)","opening_hours":"Öffnungszeiten konfiguriert","first_category":"Erste Kategorie angelegt","first_product":"Erstes Produkt angelegt","tax_profile":"Steuerprofil konfiguriert","receipt_template":"Belegvorlage ausgewählt","payment_method":"Zahlungsmethode konfiguriert","pos_device":"POS-Gerät gekoppelt","first_staff":"Erstes Personal angelegt"}},
        "reasonCodes": {"title":"Begründungs-Codes","subtitle":"Auswahllisten, die im POS bei Stornierung oder manuellem Rabatt angezeigt werden.","tabVoid":"Stornogründe","tabDiscount":"Rabattgründe","addReason":"Neuer Grund","editReason":"Grund bearbeiten","formHint":"Code muss eindeutig sein (z. B. WRONG_ORDER). Labels pro Sprache sind optional.","labelsLabel":"Sprachen","labelPlaceholder":"{locale}-Label","colCode":"Code","colLabelTr":"TR-Label","colOrder":"Reihenfolge","colApproval":"Genehmigung?","colMaxPercent":"Max %","colStatus":"Status","colActions":"Aktionen","yesApproval":"Ja","noApproval":"Nein","statusActive":"Aktiv","statusInactive":"Inaktiv","requiresApprovalLabel":"Manager-Freigabe erforderlich","maxPercentLabel":"Max. Rabatt (%)","maxPercentHint":"Maximaler Rabatt mit diesem Grund. Leer = unbegrenzt.","emptyState":"Noch keine Gründe definiert. Neuen hinzufügen.","createSuccess":"Grund erstellt","updateSuccess":"Grund aktualisiert","deleteSuccess":"Grund gelöscht","deleteError":"Löschen fehlgeschlagen","saveError":"Speichern fehlgeschlagen","deleteConfirmBody":"Grund {code} wird gelöscht. Fortfahren?"},
        "menu": {"snoozeColumn":"Verfügbarkeit","statusAvailable":"Verfügbar","statusSnoozed":"Ausverkauft","snoozedUntil":"Bis:","snoozeBulk":"Status für {count} Artikel","snoozeFor":"Dauer","snooze1h":"1 Stunde ausverkauft","snooze2h":"2 Stunden ausverkauft","snoozeEod":"Bis Tagesende ausverkauft","snoozeManual":"Bis manueller Rücknahme","snoozeClear":"Verfügbar machen (alle ausgewählten)"},
        "nav": {"rmReasonCodes":"Begründungs-Codes"},
    },
    "fr": {
        "cmdk": {"placeholder":"Rechercher pages, produits, utilisateurs, catégories…","noResults":"Aucun résultat","groupQuickActions":"Actions rapides","groupPages":"Aller à la page","groupProducts":"Produits","groupCategories":"Catégories","groupUsers":"Utilisateurs","groupSwitchTenant":"Changer de restaurant","actionNewOrder":"Nouvelle commande","actionPublishMenu":"Publier le menu","actionMwstReport":"Exporter le rapport TVA (MWST)"},
        "setupProgress": {"pill":"Config {percent}%","title":"Progression de la configuration","subtitle":"{done}/{total} étapes terminées","complete":"Configuration terminée","dismiss":"Masquer","optional":"facultatif","steps":{"tenant_created":"Restaurant créé","admin_user":"Premier compte administrateur créé","tenant_info":"Infos du restaurant remplies (adresse / téléphone)","opening_hours":"Horaires d'ouverture configurés","first_category":"Première catégorie ajoutée","first_product":"Premier produit ajouté","tax_profile":"Profil de taxe configuré","receipt_template":"Modèle de reçu sélectionné","payment_method":"Méthode de paiement configurée","pos_device":"Appareil POS apparié","first_staff":"Premier employé ajouté"}},
        "reasonCodes": {"title":"Codes motifs","subtitle":"Sélecteurs affichés au POS lors d'une annulation ou d'une remise manuelle.","tabVoid":"Motifs d'annulation","tabDiscount":"Motifs de remise","addReason":"Nouveau motif","editReason":"Modifier le motif","formHint":"Le code doit être unique (ex. WRONG_ORDER). Libellés par langue facultatifs.","labelsLabel":"Langues","labelPlaceholder":"Libellé {locale}","colCode":"Code","colLabelTr":"Libellé TR","colOrder":"Ordre","colApproval":"Approbation ?","colMaxPercent":"Max %","colStatus":"Statut","colActions":"Actions","yesApproval":"Oui","noApproval":"Non","statusActive":"Actif","statusInactive":"Inactif","requiresApprovalLabel":"Approbation du manager requise","maxPercentLabel":"Remise max (%)","maxPercentHint":"Remise maximale avec ce motif. Vide = illimité.","emptyState":"Aucun motif défini. Ajoutez-en un.","createSuccess":"Motif créé","updateSuccess":"Motif mis à jour","deleteSuccess":"Motif supprimé","deleteError":"Échec de la suppression","saveError":"Échec de l'enregistrement","deleteConfirmBody":"Le motif {code} sera supprimé. Continuer ?"},
        "menu": {"snoozeColumn":"Disponibilité","statusAvailable":"Disponible","statusSnoozed":"Épuisé","snoozedUntil":"Jusqu'à :","snoozeBulk":"Statut pour {count} articles","snoozeFor":"Durée","snooze1h":"Épuisé 1 heure","snooze2h":"Épuisé 2 heures","snoozeEod":"Épuisé jusqu'à la fin de journée","snoozeManual":"Épuisé jusqu'à réactivation manuelle","snoozeClear":"Rendre disponible (tous sélectionnés)"},
        "nav": {"rmReasonCodes":"Codes motifs"},
    },
    "it": {
        "cmdk": {"placeholder":"Cerca pagine, prodotti, utenti, categorie…","noResults":"Nessun risultato","groupQuickActions":"Azioni rapide","groupPages":"Vai alla pagina","groupProducts":"Prodotti","groupCategories":"Categorie","groupUsers":"Utenti","groupSwitchTenant":"Cambia ristorante","actionNewOrder":"Nuovo ordine","actionPublishMenu":"Pubblica menu","actionMwstReport":"Esporta rapporto IVA (MWST)"},
        "setupProgress": {"pill":"Setup {percent}%","title":"Avanzamento configurazione","subtitle":"{done}/{total} passi completati","complete":"Configurazione completa","dismiss":"Nascondi","optional":"facoltativo","steps":{"tenant_created":"Ristorante creato","admin_user":"Primo account amministratore creato","tenant_info":"Dati del ristorante inseriti (indirizzo / telefono)","opening_hours":"Orari di apertura configurati","first_category":"Prima categoria aggiunta","first_product":"Primo prodotto aggiunto","tax_profile":"Profilo fiscale configurato","receipt_template":"Modello di ricevuta selezionato","payment_method":"Metodo di pagamento configurato","pos_device":"Dispositivo POS abbinato","first_staff":"Primo personale aggiunto"}},
        "reasonCodes": {"title":"Codici motivo","subtitle":"Selettori mostrati nel POS durante l'annullamento di un ordine o l'applicazione di uno sconto manuale.","tabVoid":"Motivi di annullamento","tabDiscount":"Motivi di sconto","addReason":"Nuovo motivo","editReason":"Modifica motivo","formHint":"Il codice deve essere unico (es. WRONG_ORDER). Etichette per lingua opzionali.","labelsLabel":"Lingue","labelPlaceholder":"Etichetta {locale}","colCode":"Codice","colLabelTr":"Etichetta TR","colOrder":"Ordine","colApproval":"Approvazione?","colMaxPercent":"Max %","colStatus":"Stato","colActions":"Azioni","yesApproval":"Sì","noApproval":"No","statusActive":"Attivo","statusInactive":"Inattivo","requiresApprovalLabel":"Richiede approvazione del manager","maxPercentLabel":"Sconto massimo (%)","maxPercentHint":"Sconto massimo consentito con questo motivo. Vuoto = illimitato.","emptyState":"Nessun motivo definito. Aggiungine uno.","createSuccess":"Motivo creato","updateSuccess":"Motivo aggiornato","deleteSuccess":"Motivo eliminato","deleteError":"Eliminazione non riuscita","saveError":"Salvataggio non riuscito","deleteConfirmBody":"Il motivo {code} verrà eliminato. Continuare?"},
        "menu": {"snoozeColumn":"Disponibilità","statusAvailable":"Disponibile","statusSnoozed":"Esaurito","snoozedUntil":"Fino a:","snoozeBulk":"Stato per {count} articoli","snoozeFor":"Durata","snooze1h":"Esaurito 1 ora","snooze2h":"Esaurito 2 ore","snoozeEod":"Esaurito fino a fine giornata","snoozeManual":"Esaurito fino a reset manuale","snoozeClear":"Rendi disponibile (tutti selezionati)"},
        "nav": {"rmReasonCodes":"Codici motivo"},
    },
}


def deep_merge(dst, src):
    """Fill missing keys only. Re-runs are safe."""
    for k, v in src.items():
        if isinstance(v, dict) and isinstance(dst.get(k), dict):
            deep_merge(dst[k], v)
        elif k not in dst:
            dst[k] = v


for loc, additions in TRANSLATIONS.items():
    fp = MSG_DIR / f"{loc}.json"
    raw = json.loads(fp.read_text(encoding="utf-8"))
    deep_merge(raw, additions)
    fp.write_text(json.dumps(raw, ensure_ascii=False, indent=2) + "\n",
                  encoding="utf-8")
    print(loc + ".json merged")

print("Done.")
